name: Remove Labels on New Push

on:
  pull_request_target:
    types: [opened, synchronize] # Trigger on PR opened or new commits pushed

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Grant permission to modify labels
    steps:
      - name: Remove specific labels
        uses: actions-ecosystem/action-remove-labels@v1 # Use a marketplace action for label removal
        with:
          labels: "ready,deployed" # Comma-separated list of labels to remove
